version: '3'

services:

  apachephp:
    build: 
      context: './images/apachephp/'
    ports:
      - "80:80"
    volumes:
      - /mnt/opencart/upload/:/var/www/html/
    container_name: "apachephp"
    image: apachephp

  mariadb:
    image: mariadb:10.5
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/conf:/etc/mysql
    env_file:
     - /etc/.env
    environment:
      TZ: "Europe/Kiev"
    ports:
      - "3306:3306"
    container_name: "mariadb"
    
